version: '3'

services:
  demo:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://arquiWeb:3306/arquiweb?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      arquiWeb:
          condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M
  arquiWeb:
    image: mysql:8.4.0 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: arquiWeb
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10